Added error C2338 to the ignore list because IntelliSense is too stupid to handle static_assert statements by design (see http://connect.microsoft.com/VisualStudio/feedback/details/533466 for details).